spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile:github,ldap}
  jpa:
    properties:
      hibernate:
        query:
          plan_cache_max_size: 192 # limit query plan cache max size
  main:
    allow-bean-definition-overriding: true

server:
  port: 8070
  compression:
    enabled: true
  tomcat:
    use-relative-redirects: true

logging:
  file:
    name: /opt/logs/100003173/apollo-portal.log

management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP
    ldap:
      enabled: false # disable ldap health check by default

#  /******************     added by pegasus     ****************************/
apollo:
  encrypt:
    app_id: ${app_id:encrypt.key}
    private_key_name: ${private_key_name:private.key}
    public_key_name: ${public_key_name:public.key}
#  /******************     added by pegasus     ****************************/